package id.ac.poliban.mi.firah.listviewmakanan;

import java.util.ArrayList;
import java.util.List;

public class CountryMenu {
    static List<Country> getAllCount() {
        List<Country> data = new ArrayList<>();
        {
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Rendang_daging_sapi_asli_Padang.JPG/375px-Rendang_daging_sapi_asli_Padang.JPG", "Rendang - Sumatra Barat","Rendang atau randang (Jawi: رندڠ) adalah masakan daging dengan bumbu rempah-rempah yang berasal dari Minangkabau. Masakan ini dihasilkan dari proses memasak yang dipanaskan berulang-ulang menggunakan santan sampai kuahnya kering sama sekali. Proses memasaknya memakan waktu berjam-jam (biasanya sekitar empat jam) hingga yang tinggal hanyalah potongan daging berwarna hitam pekat. Dalam suhu ruangan, rendang dapat bertahan hingga berminggu-minggu. Rendang yang dimasak dalam waktu yang lebih singkat dan santannya belum mengering disebut kalio, berwarna cokelat terang keemasan."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Rendang_dish_closeup.jpg/225px-Rendang_dish_closeup.jpg","Kalio - Sumatra Barat","Kalio adalah sebutan dari rendang setengah jadi, yang masih berwarna kecoklatan dibanding rendang yang berwarna cokelat kehitaman. Kalio bertekstur lengket dan basah dengan aroma karamel yang kuat, sementara rendang lebih kering, bertekstur kasar, dan mengeluarkan aroma rempah yang tajam. Umumnya kalio dijual sebagai rendang di Rumah Makan Padang di luar Sumatra Barat karena durasi memasak lebih pendek sehingga lebih praktis dan ekonomis untuk disajikan. Selain itu, rasanya tidak terlalu pedas dan daging yang dimasak juga tidak sekeras rendang."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/id/thumb/c/c4/Ayam-Betutu-%E2%80%93-Bali.jpg/330px-Ayam-Betutu-%E2%80%93-Bali.jpg", "Ayam Betutut - Bali", "Betutu adalah lauk yang terbuat dari ayam atau bebek yang utuh yang berisi bumbu, kemudian dipanggang dalam api sekam. Betutu ini telah dikenal di seluruh kabupaten di Bali. Salah satu produsen betutu adalah desa Melinggih, kecamatam payangan kabupaten Gianyar. Ayam betutu juga merupakan makanan khas Gilimanuk."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Satay_Lilit.jpg/375px-Satay_Lilit.jpg","Sate Lilit - Bali", "Sate Lilit adalah sebuah varian sate asal Bali.[1] Sate ini terbuat dari daging babi, ikan, ayam, daging sapi, atau bahkan kura-kura yang dicincang, kemudian dicampur dengan parutan kelapa, santan, jeruk nipis, bawang merah, dan merica. Daging cincang yang telah berbumbu dilekatkan pada sebuah bambu atau tebu, kemudian dipanggang di atas arang. Tidak seperti sate lainnya yang dibuat dengan tusuk sate yang sempit dan tajam, tusuk sate lilit berbentuk datar dan lebar. Permukaan yang lebih luas memungkinkan daging cincang untuk melekat. Istilah lilit dalam bahasa Bali dan Indonesia berarti \"membungkus\", yang sesuai untuk cara pembuatan sate ini."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Gulai_ayam.JPG/375px-Gulai_ayam.JPG","Gulai - Madura","Gulai adalah masakan berbahan baku daging ayam, aneka ikan, kambing, sapi, jeroan, atau sayuran seperti nangka muda dan daun singkong, yang diolah dalam kuah bumbu rempah yang bercita rasa gurih. Ciri khas gulai adalah bumbunya yang kaya rempah antara lain kunyit, ketumbar, lada, lengkuas, jahe, cabai merah, bawang merah, bawang putih, adas, pala, serai, kayu manis dan jintan yang dihaluskan, dicampur, kemudian dimasak dalam santan.[1] Masakan ini yang memiliki ciri khas berwarna kuning karena pengaruh sari kunyit. Makanan ini dianggap sebagai bentuk lain dari kari, dan secara internasional sering disebut sebagai kari ala Indonesia,[2] meskipun dalam seni kuliner Indonesia juga ditemukan kari."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Gado_gado.jpg/375px-Gado_gado.jpg","Gado Gado - Malang","Gado-gado adalah salah satu makanan yang berasal dari Indonesia yang berupa sayur-sayuran yang direbus dan dicampur jadi satu, dengan bumbu kacang atau saus dari kacang tanah dan yang dihaluskan disertai irisan telur dan pada umumnya banyak yang menambahkan kentang rebus yang sudah dihaluskan untuk saus gado gado kentang rebus dimasak bersamaan dengan bumbu kacang kemudian di atasnya ditaburi bawang goreng. Sedikit emping goreng atau kerupuk (ada juga yang memakai kerupuk udang) juga ditambahkan."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Nasi_Rawon_A.JPG/330px-Nasi_Rawon_A.JPG","Rawon - Jawa Timur", "Rawon adalah masakan Indonesia berupa sup daging berkuah hitam sebagai campuran bumbu khas yang menggunakan kluwek. Rawon, meskipun dikenal sebagai masakan khas Jawa Timur, dikenal pula oleh masyarakat Jawa Tengah sebelah timur (daerah Surakarta)."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Tumpeng_Slametan_IGDA.JPG/420px-Tumpeng_Slametan_IGDA.JPG","Nasi Tumpeng - Yogyakarta","Nasi Tumpeng adalah cara penyajian nasi yang berdibentuk kerucut dan ditata bersama dengan lauk-pauknya; karena itu disebut pula 'nasi tumpeng'. Olahan nasi yang dipakai umumnya berupa nasi kuning, meskipun kerap juga digunakan nasi putih biasa atau nasi uduk. Cara penyajian nasi ini khas Jawa atau masyarakat Betawi keturunan Jawa dan biasanya dibuat pada saat kenduri atau perayaan suatu kejadian penting. Meskipun demikian, masyarakat Indonesia sudah mengenal kegiatan ini secara umum."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Nasi_Gudeg.jpg/330px-Nasi_Gudeg.jpg", "Gudeg - Malang","Gudeg (ejaan bahasa Jawa: ꦒꦸꦝꦼꦒ꧀\u200B, Gudheg) adalah makanan khas Yogyakarta dan Jawa Tengah yang terbuat dari nangka muda yang dimasak dengan santan. Perlu waktu berjam-jam untuk membuat masakan ini. Warna coklat biasanya dihasilkan oleh daun jati yang dimasak bersamaan. Gudeg dimakan dengan nasi dan disajikan dengan kuah santan kental (areh), ayam kampung, telur, tempe, tahu dan sambal goreng krecek."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nasi_Lemak_Sambal_Cumi_in_Indonesia_2.jpg/375px-Nasi_Lemak_Sambal_Cumi_in_Indonesia_2.jpg","Nasi Lemak - Riau", "Nasi lemak adalah jenis makanan khas suku Melayu yang lazim ditemukan di Malaysia di mana hidangan ini dianggap sebagai salah satu hidangan nasionalnya,[6] dan Indonesia (khususnya di Riau dan Kepulauan Riau). Hidangan ini pun dapat ditemukan di Singapura dan Brunei. Makanan ini biasanya dihidangkan untuk sarapan pagi."));

            return data;
        }
    }
}
